<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Borrowers List</title>
</head>

<body>
  <div class="header">
    <h1>ABG Finance</h1>
  </div>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Contact</th>
        <th>Email</th>
        <th>Address</th>
        <th>Created At</th>
      </tr>
    </thead>
    <tbody>
      @foreach($borrowers as $b)
        <tr>
          <td>{{ $b->id }}</td>
          <td>{{ $b->fname }} {{ $b->lname }}</td>
          <td>{{ $b->contact_number }}</td>
          <td>{{ $b->email }}</td>
          <td>{{ $b->address }}</td>
          <td>{{ $b->created_at->format('M d, Y') }}</td>
        </tr>
      @endforeach
    </tbody>
  </table>


  <div class="footer">
    <p>Generated by ABG Finance | {{ now()->format('F d, Y') }}</p>
  </div>
</body>

</html>
