<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Loans List</title>
  <style>
    header {
      text-align: center;
      margin-bottom: 10px;
    }

    header h1 {
      font-size: 22px;
      margin-bottom: 4px;
    }

    header p {
      font-size: 13px;
      color: #555;
    }

    body {
      font-family: DejaVu Sans, sans-serif;
      font-size: 12px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
    }

    th,
    td {
      border: 1px solid #999;
      padding: 6px;
      text-align: left;
    }

    th {
      background-color: #f0f0f0;
    }

    .page-break {
      page-break-before: always;
    }

  </style>
</head>

<body>
  <div class="header">
    <h1>ABG Finance</h1>
  </div>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Borrower</th>
        <th>Amount</th>
        <th>Terms</th>
        <th>Status</th>
        <th>Total Amount Payable</th>
        <th>Due Date</th>
      </tr>
    </thead>
    <tbody>
      @foreach($loans as $loan)
      <tr>
        <td>{{ $loan->id }}</td>
        <td>{{ $loan->borrower->fname }} {{ $loan->borrower->lname }}</td>
        <td>&#x20B1;{{ number_format($loan->loan_amount, 2) }}</td>
        <td>{{ $loan->terms }} mo.</td>
        <td>{{ ucfirst($loan->status) }}</td>
        <td>
          &#x20B1;
          {{ $loan->status === 'rejected'
        ? number_format(0, 2)
        : number_format($loan->remaining_balance, 2) 
                }}
        </td>

        <td>{{ \Carbon\Carbon::parse($loan->due_date)->format('M d, Y') }}</td>
      </tr>
      @endforeach
    </tbody>
  </table>

  <div class="footer">
    <p>Generated by ABG Finance | {{ now()->format('F d, Y') }}</p>
  </div>
</body>

</html>
