<!DOCTYPE html>
<html>

<head>
    <title>{{ ucfirst($reportType) }} Payments Report</title>
    @include('pdf.styles')
</head>

<body>
    <div class="header">
        <h1>ABG Finance</h1>
    </div>
    <h2>{{ ucfirst($reportType) }} Payments Report</h2>
    <p>Period: {{ $periodLabel }}</p>

    <table>
        <thead>
            <tr>
                <th>No.</th>
                <th>Borrower</th>
                <th>Loan ID</th>
                <th>Amount</th>
                <th>Penalty</th>
                <th>Total Paid</th>
                <th>Date Paid</th>
            </tr>
        </thead>
        <tbody>
            @php
                $totalAmount = 0;
                $totalPenalty = 0;
                $grandTotal = 0;
            @endphp
            @foreach($payments as $index => $payment)
                @php
                    $totalAmount += $payment->amount;
                    $totalPenalty += $payment->penalty;
                    $grandTotal += $payment->total_paid;
                @endphp
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $payment->loan->borrower->fname }} {{ $payment->loan->borrower->lname }}</td>
                    <td>{{ $payment->loan->id }}</td>
                    <td class="numeric">₱{{ number_format($payment->amount, 2) }}</td>
                    <td class="numeric">₱{{ number_format($payment->penalty, 2) }}</td>
                    <td class="numeric">₱{{ number_format($payment->total_paid, 2) }}</td>>
                    <td>{{ \Carbon\Carbon::parse($payment->created_at)->format('M d, Y') }}</td>
                </tr>
            @endforeach
            <!-- Totals -->
            <tr>
                <th colspan="3" class="text-right">Totals:</th>
                <th class="numeric">₱{{ number_format($totalAmount, 2) }}</th>
                <th class="numeric">₱{{ number_format($totalPenalty, 2) }}</th>
                <th class="numeric">₱{{ number_format($grandTotal, 2) }}</th>
                <th colspan="2"></th>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        Generated by ABG Finance &bull; Page {PAGE_NUM} of {PAGE_COUNT}
    </div>

</body>

</html>
