<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Statement of Account - {{ $borrower->fname }} {{ $borrower->lname }}</title>
  <style>
    body {
      font-family: 'DejaVu Sans', sans-serif;
      color: #333;
      font-size: 12px;
      margin: 10px;
    }

    h1,
    h2,
    h3 {
      color: #1f2937;
      margin-bottom: 8px;
    }

    .header {
      text-align: center;
      margin-bottom: 10px;
    }

    .header h1 {
      font-size: 22px;
      margin-bottom: 4px;
    }

    .header p {
      font-size: 13px;
      color: #555;
    }

    .section {
      margin-bottom: 20px;
    }

    .details-table td {
      padding: 4px 8px;
      vertical-align: top;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 8px;
    }

    th,
    td {
      border: 1px solid #ddd;
      padding: 6px 8px;
      text-align: left;
    }

    th {
      background: #f3f4f6;
      font-weight: bold;
    }

    .loan-box {
      margin-top: 25px;
      border: 1px solid #ccc;
      padding: 12px;
      border-radius: 6px;
    }

    .text-right {
      text-align: right;
    }

    .text-center {
      text-align: center;
    }

    .footer {
      text-align: center;
      font-size: 10px;
      color: #777;
      margin-top: 40px;
      border-top: 1px solid #ccc;
      padding-top: 10px;
    }
  </style>
</head>

<body>
  <div class="header">
    <h1>ABG Finance</h1>
    <p><strong>Statement of Account</strong></p>
  </div>

  {{-- Borrower Details --}}
  <div class="section">
    <h2>Borrower Information</h2>
    <table class="details-table">
      <tr>
        <td><strong>Name:</strong></td>
        <td>{{ $borrower->fname }} {{ $borrower->lname }}</td>
        <td><strong>Phone:</strong></td>
        <td>{{ $borrower->contact_number }}</td>
      </tr>
      <tr>
        <td><strong>Email:</strong></td>
        <td>{{ $borrower->email ?? '—' }}</td>
        <td><strong>Address:</strong></td>
        <td>{{ $borrower->address ?? '—' }}</td>
      </tr>
    </table>
  </div>

  {{-- Loans --}}
  @foreach ($borrower->loans as $loan)
    <div class="loan-box">
      <h3>Loan ID: {{ $loan->id }}</h3>
      <table class="details-table">
        <tr>
          <td><strong>Loan Amount:</strong></td>
          <td>₱{{ number_format($loan->loan_amount, 2) }}</td>
          <td><strong>Terms:</strong></td>
          <td>{{ $loan->terms }} months</td>
        </tr>
        <tr>
          <td><strong>Payable per Term:</strong></td>
          <td>₱{{ number_format($loan->payable_per_term ?? 0, 2) }}</td>
          <td><strong>Status:</strong></td>
          <td>{{ ucfirst($loan->loan_status ?? 'N/A') }}</td>
        </tr>
      </table>

      <h4 style="margin-top: 10px;">Payment History</h4>
      <table>
        <thead>
          <tr>
            <th>No. of Payments</th>
            <th>Amount Paid</th>
            <th>Term</th>
            {{-- <th>Penalty</th>
            <th>Total Paid</th> --}}
            <th>Date</th>
            <th>Reference</th>
          </tr>
        </thead>
        <tbody>
          @forelse ($loan->payments as $payment)
            <tr>
              <td class="text-center">{{ $loop->iteration }}</td>
              <td class="text-right">₱{{ number_format($payment->amount, 2) }}</td>
              <td class="text-center">{{ $payment->month }}</td>
              {{-- <td class="text-right">₱{{ number_format($payment->penalty, 2) }}</td>
              <td class="text-right"><strong>₱{{ number_format($payment->totalPayable, 2) }}</strong></td> --}}
              <td>{{ $payment->created_at->format('M d, Y') }}</td>
              <td class="text-center">{{ $payment->reference_id }}</td>
            </tr>
          @empty
            <tr>
              <td colspan="7" class="text-center text-gray-500">No payments recorded.</td>
            </tr>
          @endforelse
        </tbody>
      </table>
    </div>
  @endforeach

  <div class="footer">
    <p>Generated by ABG Finance | {{ now()->format('F d, Y') }}</p>
  </div>
</body>

</html>
